---

name: "Ruby on Rails CD"

on:
  push:
    branches: [ "main" ]
  # workflow_run:
  #   workflows: ["Ruby on Rails CI"]
  #   types:
  #     - completed

jobs:
  deployDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: RubyAppStack
          template: .github/config/cfn_deployment.yml
          no-fail-on-empty-changeset: "1"

...