---

name: "Ruby on Rails CD"

on:
  workflow_run:
    workflows: ["Ruby on Rails CI"]
    types:
      - completed

jobs:
  deployDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download aws and create cfn stack
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rubytodo-ci
          IMAGE_TAG: latest
        run: |
          sudo curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
          sudo chmod +x install-aws.sh
          sudo bash install-aws.sh "v2" "amd64"
          rm install-aws.sh  
          aws cloudformation update-stack --stack-name RubyAppStack --template-body file://.github/config/cfn_deployment.yml --capabilities CAPABILITY_NAMED_IAM

...